# Generated by Django 3.0 on 2021-03-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnp_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentplaced',
            name='id_no',
            field=models.CharField(max_length=100),
        ),
    ]
