from django.db import models


# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=100)
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    branch = models.CharField(max_length=100)


class Resume(models.Model):
    number = models.CharField(max_length=100)
    user = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    branch = models.CharField(max_length=100)
    gender = models.CharField(max_length=100)
    date = models.DateField(max_length=100)
    languages = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    objective = models.CharField(max_length=100)
    sem1 = models.FloatField(blank=True, null=True)
    sem1f = models.FileField(upload_to="ygygGYjhd#jdj123", blank=True)
    sem2 = models.FloatField(blank=True, null=True)
    sem2f = models.FileField(upload_to="ygygGYjhd#jdj123", blank=True)
    diploma = models.FloatField(blank=True, null=True)
    diplomaf = models.FileField(upload_to="ygygGYjhd#jdj123", blank=True)
    diploma_inst = models.CharField(max_length=100, null=True)
    diploma_year = models.CharField(max_length=100, null=True)
    sem3 = models.FloatField(blank=True, null=True)
    sem3f = models.FileField(upload_to="ygygGYjhd#jdj123", blank=True)
    sem4 = models.FloatField(blank=True, null=True)
    sem4f = models.FileField(upload_to="ygygGYjhd#jdj123", blank=True)
    sem5 = models.FloatField(blank=True, null=True)
    sem5f = models.ImageField(upload_to="ygygGYjhd#jdj123", blank=True)
    sem6 = models.FloatField(blank=True, null=True)
    sem6f = models.FileField(upload_to="ygygGYjhd#jdj123", blank=True)
    sem7 = models.FloatField(blank=True, null=True)
    sem7f = models.FileField(upload_to="ygygGYjhd#jdj123", blank=True)
    sem8 = models.FloatField(blank=True, null=True)
    sem8f = models.FileField(upload_to="ygygGYjhd#jdj123", blank=True)
    agg = models.FloatField()
    ssc_marks = models.FloatField()
    sscf = models.FileField(upload_to="ygygGYjhd#jdj123", blank=True)
    ssc_institute = models.CharField(max_length=200)
    ssc_year = models.CharField(max_length=100)
    hsc_marks = models.FloatField(blank=True, null=True)
    hscf = models.FileField(upload_to="ygygGYjhd#jdj123", blank=True)
    hsc_institute = models.CharField(max_length=200, null=True)
    hsc_year = models.CharField(max_length=100, null=True)
    be_proj = models.CharField(max_length=100)
    te_proj = models.CharField(max_length=100)
    tech_prof = models.CharField(max_length=200)
    awards = models.CharField(max_length=200)
    hobbies = models.CharField(max_length=200)
    oneto6 = models.CharField(max_length=100)
    dream = models.CharField(max_length=100)
    sperc = models.IntegerField()
    lock = models.BooleanField()