# Generated by Django 2.1 on 2020-08-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('user', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('languages', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('objective', models.CharField(max_length=100)),
                ('sem1', models.FloatField()),
                ('sem1f', models.FileField(blank=True, upload_to='ygygGYjhd#jdj123')),
                ('sem2', models.FloatField()),
                ('sem2f', models.FileField(blank=True, upload_to='ygygGYjhd#jdj123')),
                ('diploma', models.FloatField()),
                ('diplomaf', models.FileField(blank=True, upload_to='ygygGYjhd#jdj123')),
                ('diploma_inst', models.CharField(max_length=100)),
                ('diploma_year', models.CharField(max_length=100)),
                ('sem3', models.FloatField()),
                ('sem3f', models.FileField(blank=True, upload_to='ygygGYjhd#jdj123')),
                ('sem4', models.FloatField()),
                ('sem4f', models.FileField(blank=True, upload_to='ygygGYjhd#jdj123')),
                ('sem5', models.FloatField()),
                ('sem5f', models.ImageField(blank=True, upload_to='ygygGYjhd#jdj123')),
                ('sem6', models.FloatField()),
                ('sem6f', models.FileField(blank=True, upload_to='ygygGYjhd#jdj123')),
                ('sem7', models.FloatField()),
                ('sem7f', models.FileField(blank=True, upload_to='ygygGYjhd#jdj123')),
                ('sem8', models.FloatField()),
                ('sem8f', models.FileField(blank=True, upload_to='ygygGYjhd#jdj123')),
                ('agg', models.FloatField()),
                ('ssc_marks', models.FloatField()),
                ('sscf', models.FileField(blank=True, upload_to='ygygGYjhd#jdj123')),
                ('ssc_institute', models.CharField(max_length=200)),
                ('ssc_year', models.CharField(max_length=100)),
                ('hsc_marks', models.FloatField()),
                ('hscf', models.FileField(blank=True, upload_to='ygygGYjhd#jdj123')),
                ('hsc_institute', models.CharField(max_length=200)),
                ('hsc_year', models.CharField(max_length=100)),
                ('be_proj', models.CharField(max_length=100)),
                ('te_proj', models.CharField(max_length=100)),
                ('tech_prof', models.CharField(max_length=200)),
                ('awards', models.CharField(max_length=200)),
                ('hobbies', models.CharField(max_length=200)),
                ('oneto6', models.CharField(max_length=100)),
                ('dream', models.CharField(max_length=100)),
                ('sperc', models.IntegerField()),
                ('lock', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
            ],
        ),
    ]
